version: '3'

services:
  rest-blogposts:
    container_name: rest-blogposts
    build: .
    environment:
      - DB_HOST = mysql
      - DB_USER = root
      - DB_PASSWORD = password
    ports:
      - "8081:8080"
    network_mode: bridge